# Generated by Django 3.2 on 2023-10-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_tblalumno_tblalumnos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblProfesor',
            new_name='TblProfesores',
        ),
        migrations.DeleteModel(
            name='TblMatricula',
        ),
    ]
