# Generated by Django 3.2 on 2023-10-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20231010_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblprofesores',
            name='profesor_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
